<?php
function trms_admin() {
  $form = array();

  $form['trms_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Full URL to the Tightrope Media Server web services'),
    '#size' => 60,
    '#default_value' => variable_get('trms_url', 60),
    '#maxlength' => 60,
    '#description' => t("Example: http://media.server.com:80/CablecastWS"),
    '#required' => TRUE,
  );

  $form['trms_channel'] = array(
    '#type' => 'textfield',
    '#title' => t('TRMS Channel ID'),
    '#size' => 10,
    '#default_value' => variable_get('trms_channel', 3),
    '#maxlength' => 3,
    '#description' => t("TRMS channel ID for this module. All functions will operate on this channel only"),
    '#required' => TRUE,
  );

  $form['trms_username'] = array(
    '#type' => 'textfield',
    '#title' => t('User ID'),
    '#size' => 10,
    '#default_value' => variable_get('trms_username', 50),
    '#maxlength' => 50,
    '#description' => t("User must have rights to update shows and the schedule"),
    '#required' => TRUE,
  );

  $form['trms_password'] = array(
    '#type' => 'password',
    '#title' => t('User ID\'s password'),
    '#size' => 10,
    '#maxlength' => 50,
    '#description' => t("Password for the above user name"),
    '#required' => TRUE,
  );


  return system_settings_form($form);
}

function trms_menu() {

  $items = array();

  $items['admin/settings/trms'] = array(
    'title' => 'Tightrope Media Server settings',
    'description' => 'TRMS URL and authentication configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('trms_admin'),
    'access arguments' => array('admin trms settings'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}
?>
